### ISSUE TITLE
Change Anastasia description

### ISSUE THREAD

**Issue by korshuk** [IlyaRucavitcyn/psyclub.by#4]
В описании проблем, с которыми мы работаем, в тексте "Наши особенности" напишите обо мне следующее:

Специализация Анастасии - перинатальная психология. К ней обращаются за психологической поддержкой при беременности, бесплодии, потере ребенка, аборте, ЭКО, суррогатном материнстве, усыновлении.

Далее выделяю кавычками те слова, которые следует сделать активными ссылками: 
Специализация Анастасии - "перинатальная психология". К ней обращаются за психологической поддержкой при "беременности", "бесплодии", "потере ребенка", "аборте", "ЭКО", "суррогатном материнстве", "усыновлении".
Небольшая задача, для оттачивания навыка ставить ссылки)))
Цитата: 
В консоли блога в рубрике "Проблемы" я сделала записи для этих ссылок:

"перинатальная психология" должна быть привязана к записи в блоге "чем может помочь перинатальный психолог?"

"беременности" должна быть привязана к записи в блоге "психологическая помощь при беременности"

"бесплодии" должна быть привязана к записи в блоге "психологические причины бесплодия"

"потере ребенка"  должна быть привязана к записи в блоге "перинатальные потери"

"аборте" должна быть привязана к записи в блоге "пред- и постабортное консультирование"

"ЭКО"  должна быть привязана к записи в блоге "психологическая поддержка при экстракорпоральном оплодотворении"

"суррогатном материнстве" должна быть привязана к записи в блоге "суррогатное материнство"

"усыновлении" должна быть привязана к записи в блоге "консультирование в ситуации усыновления"

Спасибо за Вашу помощь. 
Если я объясняю непонятно, дайте мне знать, пожалуйста.

**Comment by IlyaRucavitcyn** [comment]
Боюсь, что Анастасия добавила не все записи, описанные выше. Во сяком случае [в консоли блога в рубрике проблемы](http://psyclub.by/blog/?cat=53), а также используя [поиск по блогу](http://psyclub.by/blog/?s=%D0%BF%D1%80%D0%B5%D0%B4-+%D0%B8+%D0%BF%D0%BE%D1%81%D1%82%D0%B0%D0%B1%D0%BE%D1%80%D1%82%D0%BD%D0%BE%D0%B5+%D0%BA%D0%BE%D0%BD%D1%81%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) я не нашел ни одной статьи, начиная с рубрики "аборт" и ниже.
На текущий момент работают следующие ссылки:
- [x] "перинатальная психология"
- [x] "беременности"
- [x] "бесплодии"
- [x] "потере ребенка"

**Comment by korshuk** [comment]
Да, действительно. Давай тогда работающие ссылки остаются ссылками, а не работающие - просто текст.

**Comment by IlyaRucavitcyn** [comment]
Так и сделаем. Только ты ей напиши, когда она все создаст в блоге - доделаем ссылки.

**Comment by IlyaRucavitcyn** [comment]
[Запулил реквест](https://github.com/IlyaRucavitcyn/psyclub.by/pull/5) на это ишью
