### ISSUE TITLE
Прелоадер

### ISSUE THREAD

**Issue by korshuk** [IlyaRucavitcyn/psyclub.by#7]
Нужно сделать прелоадер)

**Comment by IlyaRucavitcyn** [comment]
Предлагаю [вот этот](http://loading.io/loader/?use=eyJzaXplIjoxMDAsInNwZWVkIjoiMiIsImNiayI6IiNmZmZmZmYiLCJjMSI6IiNjNGM0ZDIiLCJjMiI6IiNkOGQ0Y2IiLCJ0eXBlIjoiZ2VhcnMifQ==).
![preloader](https://cloud.githubusercontent.com/assets/14336732/12712163/64b62f4c-c8d7-11e5-95d8-89bbb470f382.png)

**Comment by korshuk** [comment]
а мне http://loading.io/loader/?use=eyJzaXplIjoxMDAsInNwZWVkIjoiMiIsImNiayI6IiNmZmZmZmYiLCJjMSI6IiNjNGM0ZDIiLCJjMiI6IiNkOGQ0Y2IiLCJ0eXBlIjoiZ2VhcnMifQ== кажется более подходящим. он менее острый... а люди же с проблемами на сайт приходят)))

**Comment by IlyaRucavitcyn** [comment]
слушай, может я чего-то не понимаю, но по-моему это тот же прелоадер:)

**Comment by korshuk** [comment]
точняг. я имел в виду тот, что называется ripple на той странице

**Comment by IlyaRucavitcyn** [comment]
riple - это реально для психов:)
Ок. Только я его стилизую на свой вкус.

**Comment by IlyaRucavitcyn** [comment]
[Вот так](http://loading.io/loader/?use=eyJzaXplIjoxMDAsInNwZWVkIjoiMiIsImNiayI6IiNmZmZmZmYiLCJjMSI6IiNkN2Q3ZTEiLCJjMiI6IiNkN2Q3ZTEiLCJjMyI6IjIiLCJ0eXBlIjoicmlwcGxlIn0=). М?
![preloader_2](https://cloud.githubusercontent.com/assets/14336732/12719022/8ee244c8-c903-11e5-8967-0525a6707e2e.png)

**Comment by korshuk** [comment]
да

**Comment by IlyaRucavitcyn** [comment]
Выполнено
