### ISSUE TITLE
Кнопка вниз

### ISSUE THREAD

**Issue by korshuk** [IlyaRucavitcyn/psyclub.by#9]
Нужно сделать кнопочку, со стрелочкой вниз, которая при нажатии будет прокручивать экран на один экран ниже

**Comment by IlyaRucavitcyn** [comment]
Кнопку настроил. Результат можно посмотреть [тут](http://ilyarucavitcyn.github.io/psyclub.by/). Коммиты можно проследить в [этой](https://github.com/IlyaRucavitcyn/psyclub.by/commits/butDown) ветке. Посмотри, и если все хорошо - [замерджим](https://github.com/IlyaRucavitcyn/psyclub.by/pull/12)!
